# list of stages
stages:

# list of environment for CI
  - build
  - test
  - package
  
# list of stages for CD
  - testing
  - development
  - release
  - production

# list of tasks

api-build:
  image: 'node:8.12.0-alpine'
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
    - api/dist/
    - api/node_modules/
    expire_in: 1 week
  stage: build
  tags:
    - docker
  script:
    - echo "Building artifact"
    - cd api
    - npm install
    - npm run build
    - ls -al

    
  only:
    - test
    - dev
    - master
    # - /^BB-.*$/


app-build:
  image: 'node:8.12.0-alpine'
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
    - dist/
    - node_modules/
    expire_in: 1 week
  stage: build
  tags:
    - docker
  script:
    - echo "Building artifact"
    - cd app
    - npm install
    - npm run build

  only:
    - test
    - node-react
    - master
    # - /^BB-.*$/


# api-unit-test:
#   stage: test
#   tags:
#     - docker
#   script:
#     - echo "Unit test of api"
#   dependencies:
#     - api-build
#   only:
#     - test
#     - node-react
#     - master
#     # - /^BB-.*$/



# app-unit-test:
#   stage: test
#   tags:
#     - docker
#   script:
#     - echo "Unit test app"
#   dependencies:
#     - app-build
#   only:
#     - test
#     - node-react
#     - master
#     # - /^BB-.*$/


pakage-app:
  stage: package
  tags:
    - shell
  script:
    - echo "packing app"
    - ls -al
    
  dependencies:
    - app-build
  only:
    - test
    - node-react
    - master


pakage-api:
  stage: package
  tags:
    - shell
  script:
    - echo "packing api"
    - ls -al
    
  dependencies:
    - api-build
  only:
    - test
    - dev
    - master
    
deploy-to-test:
  stage: testing
  tags:
    - docker
  script:
    - echo "Deploying to Test environment"
  only:
    - test
  

deploy-to-dev:
  stage: development
  tags:
    - docker
  script:
    - echo "Deploying to Developer environment"
  only:
    - node-react

deploy-to-qa:
  stage: development
  tags:
    - docker
  script:
    - echo "Deploying to QA environment"
  
  only:
    - node-react
    

deploy-to-uat:
  stage: development
  tags:
    - docker
  script:
    - echo "Deploying to UAT environment"
  
  only:
    - node-react
    

deploy-to-release:
  stage: release
  tags:
    - docker
  script:
    - echo "Deploying to Staging environment"
  only:
    - master


deploy-to-production:
  stage: production
  tags:
    - docker
  script:
    - echo "Deploying to Production environment"
  when: manual
  only:
    - tags
    